# Generated by Django 4.2.16 on 2024-12-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveredAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="isDelivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="paidAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
