# Generated by Django 4.2.16 on 2025-01-07 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 1, 7, 7, 58, 38, 431393, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
