# Generated by Django 5.1.5 on 2025-01-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_product__id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="_id",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
