# Generated by Django 5.1.5 on 2025-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_product__id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="_id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
