# Generated by Django 5.1.5 on 2025-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_product__id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="_id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
